/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
/**
 *
 * @author mahis
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setBounds(230, 90, 835, 490);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnreservations = new javax.swing.JButton();
        btnreports = new javax.swing.JButton();
        btnguest = new javax.swing.JButton();
        btnroom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DASHBOARD");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        btnlogout.setBackground(new java.awt.Color(51, 51, 51));
        btnlogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("Log out");
        btnlogout.setBorder(null);
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 90, 35));

        jPanel1.setBackground(new java.awt.Color(107, 185, 255));

        btnreservations.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnreservations.setForeground(new java.awt.Color(51, 51, 51));
        btnreservations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/booking-online (3).png"))); // NOI18N
        btnreservations.setText("Reservations");
        btnreservations.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnreservations.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnreservations.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnreservations.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnreservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreservationsbtnreservationActionPerformed(evt);
            }
        });

        btnreports.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnreports.setForeground(new java.awt.Color(51, 51, 51));
        btnreports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/report.png"))); // NOI18N
        btnreports.setText("Reports");
        btnreports.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnreports.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnreports.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnreports.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnreports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportsActionPerformed(evt);
            }
        });

        btnguest.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnguest.setForeground(new java.awt.Color(51, 51, 51));
        btnguest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/tourist.png"))); // NOI18N
        btnguest.setText("Guests");
        btnguest.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnguest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnguest.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnguest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnguest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguestActionPerformed(evt);
            }
        });

        btnroom.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnroom.setForeground(new java.awt.Color(51, 51, 51));
        btnroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/bed.png"))); // NOI18N
        btnroom.setText("Rooms");
        btnroom.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnroom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnroom.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnroom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroombtnroomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnguest, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnreservations, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnroom, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnreports, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnroom, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnguest, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnreservations)
                    .addComponent(btnreports))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 380, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/WhatsApp Image 2024-11-20 at 11.52.37.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed

        int confirmLogout = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirmLogout == JOptionPane.YES_OPTION) {
            try {
                Login loginForm = new Login();
                loginForm.setVisible(true);
                this.dispose(); // Close the Dashboard
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Unable to logout: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnreservationsbtnreservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreservationsbtnreservationActionPerformed
        try {
            VReservation reservationForm = new VReservation();
            reservationForm.setVisible(true);
            this.dispose(); // Close the Dashboard
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unable to open Reservation Form: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnreservationsbtnreservationActionPerformed

    private void btnreportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportsActionPerformed
        try {
            Report reportForm = new Report();
            reportForm.setVisible(true);
            this.dispose(); // Close the Dashboard
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unable to open Report Form: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnreportsActionPerformed

    private void btnguestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguestActionPerformed

        try {
            VGuest guestForm = new VGuest();
            guestForm.setVisible(true);
            this.dispose(); // Close the Dashboard
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unable to open Guest Form: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguestActionPerformed

    private void btnroombtnroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroombtnroomActionPerformed
        try {
            VRoom roomForm = new VRoom();
            roomForm.setVisible(true);
            this.dispose(); // Close the Dashboard
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unable to open Room Form: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnroombtnroomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguest;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnreports;
    private javax.swing.JButton btnreservations;
    private javax.swing.JButton btnroom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
